# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: link_failure_grpc/link_failure.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'link_failure_grpc/link_failure.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$link_failure_grpc/link_failure.proto\"+\n\x12LinkFailureRequest\x12\x15\n\rsatellite_ids\x18\x01 \x03(\t\"7\n\x13LinkFailureResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2T\n\x12LinkFailureService\x12>\n\x11HandleLinkFailure\x12\x13.LinkFailureRequest\x1a\x14.LinkFailureResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'link_failure_grpc.link_failure_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LINKFAILUREREQUEST']._serialized_start=40
  _globals['_LINKFAILUREREQUEST']._serialized_end=83
  _globals['_LINKFAILURERESPONSE']._serialized_start=85
  _globals['_LINKFAILURERESPONSE']._serialized_end=140
  _globals['_LINKFAILURESERVICE']._serialized_start=142
  _globals['_LINKFAILURESERVICE']._serialized_end=226
# @@protoc_insertion_point(module_scope)
